FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

COPY *.sln .
COPY . .
WORKDIR /app/src/FlyCalculator.Web
RUN dotnet restore

RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app
COPY --from=build /app/src/FlyCalculator.Web/out ./

ENV ASPNETCORE_ENVIRONMENT Production

ENTRYPOINT ["dotnet", "FlyCalculator.Web.dll"]